### ISSUE TITLE
SVM error

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#12]
**When running SVM for classification (workflow id: 39), it returns the following error:**

_Traceback (most recent call last):
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 438, in _perform_execute
    self._state)
  File "/usr/local/juicer/juicer/transpiler.py", line 296, in transpile
    using_stdout, workflow, deploy, export_notebook)
  File "/usr/local/juicer/juicer/transpiler.py", line 108, in generate_code
    class_name = self.operations[task['operation']['slug']]
KeyError: u'svm-classification-model'_

**Comment by waltersf** [comment]
The referenced name in code for the SVM operation was incorrect. Fixed.

**Comment by alexgcsa** [comment]
**Not working yet (reopening the issue)**:

Traceback (most recent call last):
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 460, in _perform_execute
    self._emit_event(room=job_id, namespace='/stand'))
  File "/tmp/juicer_app_87_87_420.py", line 617, in main
    task_futures['aada130d-81f3-4d90-875f-309c000171de'].result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_87_87_420.py", line 616, in <lambda>
    lambda: evaluate_model_5(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_87_87_420.py", line 362, in evaluate_model_5
    parent_result = task_futures['c5f52d1a-39f3-45e8-9af4-eb0fadc7cfaa'].result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_87_87_420.py", line 355, in <lambda>
    lambda: apply_model_4(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_87_87_420.py", line 323, in apply_model_4
    out3 = model2.transform(sd15, params)
NameError: global name 'model2' is not defined
