### ISSUE TITLE
One-hot-enconder not working for categorical values?

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#131]
Hi there,

this is basically the essence of One-hot-encoder.

Trying to use here to convert categorical to numeric but it hasn't worked. It returns the following error:

"Invalid or missing parameters: requirement failed: Input column must be of type numeric but got string "

**Workflow id: 606.**

**Comment by alexgcsa** [comment]
i'm going to test it.

**Comment by alexgcsa** [comment]
@waltersf / @zilton  , I think the output is a bit odd. I haven't understand yet. Perhaps I understood something wrong.

Can you check it?

I mean, the example of the workflow 606 is based on the dataset iris. What I tried to do was to apply the one-hot encoder on the class variable, which has three possible values (Iris Setosa, Iris Versicolour  and Iris Virginica). Thus, one-hot encoder output array should have an instance for each type of Iris. Something like this:

Iris Setosa:         [0.0, 0.0, 1.0]
Iris Versicolour:  [0.0, 1.0, 0.0]
Iris Virginica:      [1.0, 0.0, 0.0]


However, the method is returning this:

![image](https://user-images.githubusercontent.com/24958541/58035962-518e2f80-7b00-11e9-9e9b-a98e732f0cb2.png)

**Comment by waltersf** [comment]
@alexgcsa "(3, [0], [1.0])" is the sparse representation for [1.0, 0, 0]. In iris case, it is not important to have such representation, but for cases where you have many labels and large number of records, it is. You'll se only 3 different values for encoding, as you can se by the first number. Then you have the position and finally the value. 
It is not possible to change this. If users have to understand the result, I suggest you to add a short description in the documentation.

**Comment by alexgcsa** [comment]
Hi @waltersf , 

I think the issue here is that the ML algorithms will not "understand" this input, in my perspective. Have you tried using it together with an ML algorithm?

I have to check, but perhaps this sparse representation could not be suitable as input.

Imagine in the case of Iris, that the class would be a given attribute with three possible values.

If I give this input to an algorithm, I think we would have information loss, because modelling "(3, [0], [1.0])" is different to modelling [1.0, 0.0, 0.0].

Scikit-learn models the way I mentioned above:

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html


Perhaps we should have a Boolean check box to define if the output will be sparse or dense. What do you think?

**Comment by alexgcsa** [comment]
@waltersf , I was thinking here. I believe this sparse representation would be basically the operation "Convert categorical to numeric".

If I understood correctly, If I have three possible values for a categorical attribute, I would have the following output:
 "(3, [0], [1.0])"
 "(3, [1], [1.0])"
 "(3, [2], [1.0])"

Now, If I have N possible values, I would have something like this:

 "(N, [0], [1.0])"
 "(N, [1], [1.0])"
 "(N, [2], [1.0])"
 "(N, [3], [1.0])"
...
 "(N, [N-2], [1.0])"
"(N, [N-1], [1.0])"

As the 3-tuple has always the same numbers for the first and last members, we would vary just the second member of the tuple. This is strictly similar to perform a conversion from a categorical to an integer value (i.e., to run the operation "Convert categorical to numeric").

Am I thinking correctly?

**Comment by alexgcsa** [comment]
@waltersf / @zilton ,

can you check the workflow 849? It stopped working...And now I am trying to run it, but it simplies collapsed and stays like running but it is taking a lot of time...

I copied and created the workflow 1036...And it worked for Naive Bayes.

**Comment by alexgcsa** [comment]
The following error appeared:

-------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 438, in _perform_execute
    self._state)

  File "/usr/local/juicer/juicer/transpiler.py", line 296, in transpile
    using_stdout, workflow, deploy, export_notebook)

  File "/usr/local/juicer/juicer/transpiler.py", line 220, in generate_code
    v = template.render(env_setup)

  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)

  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)

  File "/usr/local/juicer/juicer/spark/templates/operation.tmpl", line 57, in top-level template code
    {%-  handleinstance instance %}

  File "/usr/local/juicer/juicer/util/template_util.py", line 53, in _handle
    raise_(JuicerException(msg), None, sys.exc_info()[2])

  File "/usr/local/juicer/juicer/util/template_util.py", line 40, in _handle
    return caller()

  File "/usr/local/lib/python2.7/dist-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)

  File "/usr/local/juicer/juicer/spark/templates/operation.tmpl", line 120, in template
    {{instance.generate_code().strip() | indent(width=8, indentfirst=False)}}

  File "/usr/local/juicer/juicer/spark/ml_operation2.py", line 52, in generate_code
    return "\n".join([algorithm_code, model_code])

JuicerException: Erro de tipo analisando modelo (template) para inst\xe2ncia 8c455431-6364-4955-a8c3-dc388b3e39cf DecisionTreeModelOperation

**Comment by alexgcsa** [comment]
Hi again,

One hot enconder is not working when I have several attributes using this transformation.

Could you check the workflow 1037.

Alex

----------------------------------------------------------------

@zilton 
@waltersf

**Comment by alexgcsa** [comment]
Just to detail the issue...

I set the wrong attributes for random forest and, when I run it, it output an error.
After that I corrected the wrong attributes (they were categorical), but the error persisted.

**Comment by waltersf** [comment]
It seems to be working now

**Comment by alexgcsa** [comment]
I'm going to test it.

Thanks,

Alex

**Comment by alexgcsa** [comment]
@waltersf ,

can you give a look at the worflow 1164?

I tested one-hot-encoder, but now it is returning another thing..


-----------------------------------------
**Error:**


Traceback (most recent call last):
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 461, in _perform_execute
    self._emit_event(room=job_id, namespace='/stand'))
  File "/tmp/juicer_app_1164_1164_6352.py", line 373, in main
    task_futures['2eff5bf5-de20-4aeb-a971-987cf767e8b6'].result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_1164_1164_6352.py", line 371, in <lambda>
    lambda: naive_bayes_classifier_model_3(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_1164_1164_6352.py", line 325, in naive_bayes_classifier_model_3
    'output data': out_task_3,
NameError: global name 'out_task_3' is not defined

**Comment by alexgcsa** [comment]
Not sure why it is working for the workflow 1037, but not working for the workflow 1164.

**Comment by alexgcsa** [comment]
I think this is not working just because I didn't set the Boolean flag "Display sample(s) of output(s) (max. 50 records)" as true.

Is this because the lazy behavior of the operations?

**Comment by alexgcsa** [comment]
I was wondering if it is possible to handle this type of error, saying to the user to activate the flag "Display sample(s) of output(s) (max. 50 records)" on the 'Results' tab. And mention that without this the workflow will not produce any outputs because this is part of the lazy behavior of the operations...
