### ISSUE TITLE
Error on the workflow 1233

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#199]
Hi,

the workflow **1233** has presented the following error during its execution:

https://media.discordapp.net/attachments/716675996589228096/719563493191450644/unknown.png?width=1020&height=320

Is it possible to check this problem on it?

Thanks in advance.

Alex de Sá

---------------------

**Traceback (most recent call last):**

  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 456, in _perform_execute
    raise ex from None

  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 452, in _perform_execute
    self._emit_event(room=job_id, namespace='/stand'))

  File "/tmp/juicer_app_1233_1233_9618.py", line 338, in main
    task_futures['3e67b55f-be05-4b2e-9ea6-43bd56b03af5'].result()

  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.get_result()

  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in get_result
    raise self._exception

  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)

  File "/tmp/juicer_app_1233_1233_9618.py", line 335, in <lambda>
    lambda: histogram_1(spark_session, cached_state, emit_event))

  File "/tmp/juicer_app_1233_1233_9618.py", line 194, in histogram_1
    visualization, emit_event)

  File "/usr/local/juicer/juicer/service/caipirinha_service.py", line 97, in new_visualization
    caipirinha_config['auth_token'], '', json.dumps(visualization))

  File "/usr/local/juicer/juicer/service/caipirinha_service.py", line 28, in _update_caipirinha
    item_id, url, r.status_code, r.text))

RuntimeError: Erro na URL : HTTP http://caipirinha:23401/visualizations - 500 ({"status": "ERROR", "message": "Internal error"}
)

**Comment by alexgcsa** [comment]
It is an error on the Histogram operation.

**Comment by waltersf** [comment]
Duplicated #198. Already fixed.
