### ISSUE TITLE
Não consigo publicar como dashboard

### ISSUE THREAD

**Issue by helenapato** [eubr-bigsea/citrus#247]
Ao adicionar a operação "Publicar como dashboard" ao fluxo recebo um erro na execução.

![image](https://user-images.githubusercontent.com/42720360/124321983-022ae200-db55-11eb-9c5d-b347007b3b19.png)
 
Abaixo está transcrito o que aparece no campo "Detalhe do erro"

Traceback (most recent call last):
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 478, in _perform_execute
    raise ex from None
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 474, in _perform_execute
    self._emit_event(room=job_id, namespace='/stand'))
  File "/tmp/juicer_app_870_870_9694.py", line 885, in main
    task_futures['152761ba-d3a4-45a3-9210-b6b3ee9d4718'].result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_870_870_9694.py", line 881, in <lambda>
    lambda: publish_as_visualization_6(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_870_870_9694.py", line 827, in publish_as_visualization_6
    9694, '152761ba-d3a4-45a3-9210-b6b3ee9d4718', visualizations, emit_event)
  File "/usr/local/juicer/juicer/service/caipirinha_service.py", line 81, in new_dashboard
    json.dumps(data, sort_keys=True))
  File "/usr/local/juicer/juicer/service/caipirinha_service.py", line 28, in _update_caipirinha
    item_id, url, r.status_code, r.text))
RuntimeError: Erro na URL : HTTP http://caipirinha:23401/dashboards - 401 ({"status": "ERROR", "message": "Validation error", "errors": {"is_public": ["Missing data for required field."]}}
)

Estou usando a versão md do LEMONADE no navegador Firefox.

**Comment by waltersf** [comment]
É um erro de configuração na instalação. Tenta novamente, por favor.

**Comment by helenapato** [comment]
Instalação? Estou usando a versão web, não instalei o Lemonade localmente. Tentei novamente e recebi o mesmo erro.

**Comment by waltersf** [comment]
Desculpe, instalação no servidor. Somente agora consegui pará-lo e atualizar. Por favor, teste novamente e relate se ainda ocorre o erro.

**Comment by helenapato** [comment]
O erro não está mais ocorrendo, consegui publicar o dashboard.
