### ISSUE TITLE
Opção de salvar dados em banco de dados HIVE.

### ISSUE THREAD

**Issue by LucasLage** [eubr-bigsea/citrus#255]
Preciso salvar os dados de uma execução de um fluxo do Lemonade em um banco de dados HIVE.

**Comment by LucasLage** [comment]
Conforme conversado com o Walter, uma solução paliativa seria salvar os dados em formato de arquivo.
Mas para isso, é preciso resolver o problema que acontece, no ambiente do Ministério Publico, ao tentar salvar os dados em arquivo.

`Traceback (most recent call last):
  File "/opt/lemonade/docker-lemonade/juicer/juicer/spark/spark_minion.py", line 478, in _perform_execute
    raise ex from None
  File "/opt/lemonade/docker-lemonade/juicer/juicer/spark/spark_minion.py", line 474, in _perform_execute
    self._emit_event(room=job_id, namespace='/stand'))
  File "/tmp/juicer_app_21_21_978.py", line 1096, in main
    task_futures['ac12377b-657f-42cf-b534-5f8910e2a635'].result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_21_21_978.py", line 1085, in <lambda>
    lambda: data_writer_14(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_21_21_978.py", line 968, in data_writer_14
    header)
TypeError: 'JavaPackage' object is not callable`

**Comment by waltersf** [comment]
Implementado. Aguardando os testes,

**Comment by waltersf** [comment]
Testes OK
