### ISSUE TITLE
Random Forest Error

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#26]
**When running Random Forest for classification (workflow id: 53), it returns the following error:**

Traceback (most recent call last):
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 438, in _perform_execute
    self._state)
  File "/usr/local/juicer/juicer/transpiler.py", line 296, in transpile
    using_stdout, workflow, deploy, export_notebook)
  File "/usr/local/juicer/juicer/transpiler.py", line 220, in generate_code
    v = template.render(env_setup)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/juicer/juicer/spark/templates/operation.tmpl", line 56, in top-level template code
    {%-  handleinstance instance %}
  File "/usr/local/juicer/juicer/util/template_util.py", line 53, in _handle
    raise_(JuicerException(msg), None, sys.exc_info()[2])
  File "/usr/local/juicer/juicer/util/template_util.py", line 40, in _handle
    return caller()
  File "/usr/local/lib/python2.7/dist-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/juicer/juicer/spark/templates/operation.tmpl", line 119, in template
    {{instance.generate_code().strip() | indent(width=8, indentfirst=False)}}
  File "/usr/local/juicer/juicer/spark/ml_operation2.py", line 40, in generate_code
    return "\n".join([algorithm_code, model_code])
JuicerException: Erro de tipo analisando modelo (template) para inst\xe2ncia 8739f50e-a193-4e7c-8c5e-9a2fa38e418b RandomForestModelOperation

**Comment by waltersf** [comment]
It seems to be working now, I couldn't reproduce the error. Please, reopen this issue if it happens again.
