### ISSUE TITLE
Erro ao salvar modelo na versão md

### ISSUE THREAD

**Issue by educsantos** [eubr-bigsea/citrus#260]
Fluxo (1108) executou corretamente estando com a operação de "Salvar modelo" desativada. Com ela ativada, deu erro mesmo tentando outro nome para o modelo.

Log do erro:

Traceback (most recent call last):
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 478, in _perform_execute
    raise ex from None
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 474, in _perform_execute
    self._emit_event(room=job_id, namespace='/stand'))
  File "/tmp/juicer_app_1108_1108_10433.py", line 1011, in main
    task_futures['4e1d862c-0dd9-4495-a74f-6d014f9ec46b'].result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_1108_1108_10433.py", line 1008, in <lambda>
    lambda: save_model_5(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_1108_1108_10433.py", line 622, in save_model_5
    _save_model(model, path, name)
  File "/tmp/juicer_app_1108_1108_10433.py", line 611, in _save_model
    register_model('http://limonero:23402', model_payload, '9740600')
  File "/usr/local/juicer/juicer/service/limonero_service.py", line 86, in register_model
    raise RuntimeError(gettext("Error saving model: {})").format(r.text))
RuntimeError: Error saving model: {"message": "Internal Server Error"}
)

**Comment by waltersf** [comment]
Corrigido. Executei o fluxo 1108.
