### ISSUE TITLE
Perceptron error

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#29]
**When running Perceptron for classification (workflow id: 52), it returns the following error:**  

File "/usr/local/juicer/juicer/spark/spark_minion.py", line 438, in _perform_execute
    self._state)

  File "/usr/local/juicer/juicer/transpiler.py", line 296, in transpile
    using_stdout, workflow, deploy, export_notebook)

  File "/usr/local/juicer/juicer/transpiler.py", line 220, in generate_code
    v = template.render(env_setup)

  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)

  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)

  File "/usr/local/juicer/juicer/spark/templates/operation.tmpl", line 56, in top-level template code
    {%-  handleinstance instance %}

  File "/usr/local/juicer/juicer/util/template_util.py", line 53, in _handle
    raise_(JuicerException(msg), None, sys.exc_info()[2])

  File "/usr/local/juicer/juicer/util/template_util.py", line 40, in _handle
    return caller()

  File "/usr/local/lib/python2.7/dist-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)

  File "/usr/local/juicer/juicer/spark/templates/operation.tmpl", line 119, in template
    {{instance.generate_code().strip() | indent(width=8, indentfirst=False)}}

  File "/usr/local/juicer/juicer/spark/ml_operation2.py", line 40, in generate_code
    return "\n".join([algorithm_code, model_code])

JuicerException: Erro de tipo analisando modelo (template) para inst\xe2ncia 317dd992-b802-4921-8cab-cd18b79c0cbc PerceptronModelOperation

**Comment by alexgcsa** [comment]
**Running again another workflow (id 72), it returns another error:**


Traceback (most recent call last):

  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 460, in _perform_execute
    self._emit_event(room=job_id, namespace='/stand'))

  File "/tmp/juicer_app_72_72_305.py", line 742, in main
    task_futures['2eece051-6cae-4ab6-b189-b6c17079b453'].result()

  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()

  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)

  File "/tmp/juicer_app_72_72_305.py", line 741, in <lambda>
    lambda: evaluate_model_5(spark_session, cached_state, emit_event))

  File "/tmp/juicer_app_72_72_305.py", line 486, in evaluate_model_5
    parent_result = task_futures['bf4e85cb-108a-4668-9484-4e7431caa947'].result()

  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()

  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)

  File "/tmp/juicer_app_72_72_305.py", line 479, in <lambda>
    lambda: apply_model_4(spark_session, cached_state, emit_event))

  File "/tmp/juicer_app_72_72_305.py", line 428, in apply_model_4
    parent_result = task_futures['e08df3d7-c171-4325-810d-b2ecf2230b45'].result()

  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()

  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)

  File "/tmp/juicer_app_72_72_305.py", line 484, in <lambda>
    lambda: perceptron_classifier_model_3(spark_session, cached_state, emit_event))

  File "/tmp/juicer_app_72_72_305.py", line 342, in perceptron_classifier_model_3
    model0 = pipeline.fit(sd22)

  File "/usr/local/spark/python/pyspark/ml/base.py", line 132, in fit
    return self._fit(dataset)

  File "/usr/local/spark/python/pyspark/ml/pipeline.py", line 109, in _fit
    model = stage.fit(dataset)

  File "/usr/local/spark/python/pyspark/ml/base.py", line 132, in fit
    return self._fit(dataset)

  File "/usr/local/spark/python/pyspark/ml/wrapper.py", line 288, in _fit
    java_model = self._fit_java(dataset)

  File "/usr/local/spark/python/pyspark/ml/wrapper.py", line 285, in _fit_java
    return self._java_obj.fit(dataset._jdf)

  File "/usr/local/lib/python2.7/dist-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)

  File "/usr/local/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)

  File "/usr/local/lib/python2.7/dist-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o305.fit.
: java.util.NoSuchElementException: Failed to find a default value for layers
	at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:780)
	at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:780)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.ml.param.Params$class.getOrDefault(params.scala:779)
	at org.apache.spark.ml.PipelineStage.getOrDefault(Pipeline.scala:42)
	at org.apache.spark.ml.param.Params$class.$(params.scala:786)
	at org.apache.spark.ml.PipelineStage.$(Pipeline.scala:42)
	at org.apache.spark.ml.classification.MultilayerPerceptronClassifier.train(MultilayerPerceptronClassifier.scala:238)
	at org.apache.spark.ml.classification.MultilayerPerceptronClassifier.train(MultilayerPerceptronClassifier.scala:143)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by waltersf** [comment]
Fixed
