### ISSUE TITLE
Local Outlier Factor (LOF) Error

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#37]
Fluxo 64:

Traceback (most recent call last):
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 460, in _perform_execute
    self._emit_event(room=job_id, namespace='/stand'))
  File "/tmp/juicer_app_64_64_280.py", line 301, in main
    task_futures['5aff6923-3441-4dd0-a1d4-ec3bb903ac2d'].result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_64_64_280.py", line 300, in <lambda>
    lambda: sort_2(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_64_64_280.py", line 230, in sort_2
    parent_result = task_futures['9feaab42-c0e5-4cc5-9b09-38db2d64e511'].result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_64_64_280.py", line 228, in <lambda>
    lambda: outlier_detection_1(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_64_64_280.py", line 142, in outlier_detection_1
    algorithm = LocalOutlierFactor(minPts=5)
  File "/usr/local/spark/python/pyspark/__init__.py", line 105, in wrapper
    return func(self, **kwargs)
  File "/usr/local/juicer/juicer/spark/ext/__init__.py", line 156, in __init__
    self.uid)
  File "/usr/local/spark/python/pyspark/ml/wrapper.py", line 63, in _new_java_obj
    return java_obj(*java_args)
TypeError: 'JavaPackage' object is not callable

**Comment by waltersf** [comment]
Corrigido. Problema relacionado à instalação.
