### ISSUE TITLE
Erro Salvar dados

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#39]
Fluxo 5:

Traceback (most recent call last):
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 460, in _perform_execute
    self._emit_event(room=job_id, namespace='/stand'))
  File "/tmp/juicer_app_5_5_308.py", line 342, in main
    task_futures['83f55b38-84c2-471d-ad1e-b3ae9b8c557b'].result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_5_5_308.py", line 340, in <lambda>
    lambda: data_writer_2(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_5_5_308.py", line 245, in data_writer_2
    header)
TypeError: 'JavaPackage' object is not callable

**Comment by waltersf** [comment]
Corrigido. Por favor, reabra a issue caso haja algum problema.
