### ISSUE TITLE
Erro Mistura de Gaussianas 

### ISSUE THREAD

**Issue by karenstemartins** [eubr-bigsea/citrus#40]
Fluxo 35:

Traceback (most recent call last):
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 438, in _perform_execute
    self._state)
  File "/usr/local/juicer/juicer/transpiler.py", line 296, in transpile
    using_stdout, workflow, deploy, export_notebook)
  File "/usr/local/juicer/juicer/transpiler.py", line 108, in generate_code
    class_name = self.operations[task['operation']['slug']]
KeyError: u'gaussian-mixture-clustering-model'

**Comment by waltersf** [comment]
Karen, ainda estou corrigindo as operações de agrupamento.

**Comment by waltersf** [comment]
Corrigido
