### ISSUE TITLE
Erro na operação Salvar Modelo

### ISSUE THREAD

**Issue by matheusrleal** [eubr-bigsea/citrus#46]
Fluxo número 76.

Erro:

Traceback (most recent call last):
  File "/usr/local/juicer/juicer/spark/spark_minion.py", line 460, in _perform_execute
    self._emit_event(room=job_id, namespace='/stand'))
  File "/tmp/juicer_app_76_76_368.py", line 844, in main
    task_futures['d88149bf-2c42-47e7-a387-692d8fb43996'].result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/juicer_app_76_76_368.py", line 841, in <lambda>
    lambda: save_model_4(spark_session, cached_state, emit_event))
  File "/tmp/juicer_app_76_76_368.py", line 485, in save_model_4
    _save_model(model, path, name)
  File "/tmp/juicer_app_76_76_368.py", line 474, in _save_model
    register_model('http://limonero:23402', model_payload, '123456')
  File "/usr/local/juicer/juicer/service/limonero_service.py", line 80, in register_model
    raise RuntimeError(_("Error saving model: {})").format(r.text))
RuntimeError: Erro salvando model: {"status": "ERROR", "message": "Validation error", "errors": {"workflow_id": ["Missing data for required field."], "job_id": ["Missing data for required field."], "task_id": ["Missing data for required field."]}}

**Comment by waltersf** [comment]
Corrigido.
