### ISSUE TITLE
SVM error 2: when applying its model

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#57]
**This is an error associated to SVM classifier (I am creating a new issue as I could not reopen the previous [issue](https://github.com/eubr-bigsea/citrus/issues/12))**.

I tried to apply its model, but it did not work.

The workflow id is 87. I am trying to create a base workflow for all classification models (that I am testing) right now, differing only on the classification algorithm itself.

====================

Traceback (most recent call last):
File "/usr/local/juicer/juicer/spark/spark_minion.py", line 460, in _perform_execute
self._emit_event(room=job_id, namespace='/stand'))
File "/tmp/juicer_app_87_87_420.py", line 617, in main
task_futures['aada130d-81f3-4d90-875f-309c000171de'].result()
File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
return self.__get_result()
File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
result = self.fn(*self.args, **self.kwargs)
File "/tmp/juicer_app_87_87_420.py", line 616, in
lambda: evaluate_model_5(spark_session, cached_state, emit_event))
File "/tmp/juicer_app_87_87_420.py", line 362, in evaluate_model_5
parent_result = task_futures['c5f52d1a-39f3-45e8-9af4-eb0fadc7cfaa'].result()
File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
return self.__get_result()
File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
result = self.fn(*self.args, **self.kwargs)
File "/tmp/juicer_app_87_87_420.py", line 355, in
lambda: apply_model_4(spark_session, cached_state, emit_event))
File "/tmp/juicer_app_87_87_420.py", line 323, in apply_model_4
out3 = model2.transform(sd15, params)
NameError: global name 'model2' is not defined

**Comment by alexgcsa** [comment]
This is the workflow:

![image](https://user-images.githubusercontent.com/24958541/52559656-0ec00b80-2ddd-11e9-8509-0aa56f773118.png)

**Comment by waltersf** [comment]
Original problem was fixed (generated code was using the old implementation). But the workflow will not work because Spark SVM is a binary classifier and Iris data set has 4 classes.
